### ISSUE TITLE
Compatibility with BeautyQuests

### ISSUE THREAD

**Issue by Italoplcl** [Th3Shadowbroker/OuroborosMines#39] opened 2020-10-15 11:02 UTC
**Is your feature request related to a problem? Please describe.**
With the BeautyQuest plugin do not count the ores that are taken in an area with the flag set.
I imagine it's the same kind of incomtability that they had before with Quests and then they fixed it.
(https://www.spigotmc.org/threads/ouroboros-mines.401636/page-2#post-3713899)

**Describe the solution you'd like**
The solution is to count the ores that are removed in a region with the OM flag

Im using BeautyQuests 0.18 - Pre-release and Ouroboros-Mines 1.8.1-SNAPSHOT
The latest versions of each plugin.

I stay tuned, thank you very much.

**Comment by SkytAsul** [comment] 2020-10-15 17:34
Hey! I'm the dev of BeautyQuests. It seems like this issue is caused by the cancelling of the BlockBreakEvent.

**Comment by Italoplcl** [comment] 2020-10-15 17:36
And does that mean I have to report it to them or what? Sorry but I do not understand.

**Comment by SkytAsul** [comment] 2020-10-15 17:37
> And does that mean I have to report it to them or what? Sorry but I do not understand.

No no, it's just so that the dev knows what's the issue ^^

**Comment by Th3Shadowbroker** [comment] 2020-10-15 18:08
Hey everyone 🙂,
it is as SkytAsul said, OM takes the control over the blocks by cancelling the BlockBreakEvent.
This is the expected behaviour. In case of Quests, OM simply adds progress to the Quests, when the objective contains the mined material. I'd really like to add a similar way of support for BeautyQuests. However, I haven't completly understood the way to update the quest progress yet. 

Maybe you can give me a hint @SkytAsul ^^

I'm looking forward to hearing from you 🙂

**Comment by Italoplcl** [comment] 2020-10-15 18:31
Again, thank you very much.
I hope this helps everyone.

**Comment by Th3Shadowbroker** [comment] 2020-10-16 10:48
Alright a first version of the BeautyQuests support is implemented in the current dev build, I've posted on [Discord](https://discordapp.com/channels/490497270970581002/694945190971965541/766607318291972096). At the moment it uses reflection to update the quests progress as you can see in https://github.com/Th3Shadowbroker/OuroborosMines/commit/2354cba02b9bdf7feb30f870e2258cbda567f327.

**Comment by SkytAsul** [comment] 2020-10-16 15:55
Oh well that's a good solution ^^ I will make the "event" method public so that reflection is no longer needed. See my PR, I optimized the code a bit and removed extra useless things here and there!

**Comment by Th3Shadowbroker** [comment] 2020-10-16 16:08
Thank you for the PR! I'll have a look at it asap! 😃
Making the event method public will make it much easier and cleaner for me!

**Comment by Th3Shadowbroker** [comment] 2020-10-17 11:30
I merged #41 into the feature branch.
Testing results look good so far 👍🏼 
@Italoplcl Let me know when you're done with testing, so I can provide you with a new test build 🙂

**Closed** 2020-10-24 15:44 UTC
Labels: feature_request
